In [2]:
import numpy as np
import time

In [2]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
size=100000
py_list=list(range(size))
start_time= time.time()
sq_py_list=[x**2 for x in py_list]
end_time= time.time()

In [4]:
np_arr=np.array(py_list)
start_time= time.time()
sq_np_list=np_arr**2
end_time= time.time()
#print(sq_py_list)
print(f"total time { end_time - start_time}")

total time 0.0003056526184082031


In [5]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2D_1=[[1,2,3],[4,5,6],[7,8,9]]
print(type(arr2D_1))
print(type(arr2D))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr1 = np.zeros((2, 3), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) #range elements
print(arr5, arr5.shape)

arr5 = np.linspace(0, 100,4) #evenly spaced arrays
print(arr5, arr5.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  0.          33.33333333  66.66666667 100.        ] (4,)


In [12]:
### properties of array
arr6= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr6)
print(arr6.dtype)
print(arr6.ndim)
print(arr6.shape)
print(arr6.size)

float_arr6= arr6.astype(np.float64)
print(float_arr6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
2
(3, 3)
9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
### Reshapeing

arr7= np.array([[1,2,3],[4,5,6]])
print(arr7,arr7.shape)
reshape_arr7=arr7.reshape((3,2))
print(reshape_arr7,reshape_arr7.shape)
flat_arr7= arr7.flatten()
print(flat_arr7,flat_arr7.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [24]:
### Indexing
arr8= np.array([[1,5,6],[8,7,9]])
print(arr8[1][2])
arr9=np.array([1,2,6,5,4,8,6])
### fancy indexing
idx=[1,2,4]
print(arr9[idx])

### boolean
print(arr9[arr9>4])
print(arr9[arr9 % 2 == 0])
print(arr9[arr9 % 2 != 0])

### slicing
print(arr9[1:4])
print(arr9[::2])


9
[2 6 4]
[6 5 8 6]
[2 6 4 8 6]
[1 5]
[2 6 5]
[1 6 4 6]


In [3]:
### copy and view in numpy and list
list_arr=[1,2,3,4]
re_list_arr=list_arr[1:3]
re_list_arr[0]=200 
print(re_list_arr)
print(list_arr) ## Happend because its copied it

arr10=np.array([1,3,5,7,5,6])
re_arr10= arr10[1:4]
re_arr10[0]=100
print(re_arr10)
print(arr10)## if want to make copy then .copy



[200, 3]
[1, 2, 3, 4]
[100   5   7]
[  1 100   5   7   5   6]


In [4]:
### Multi Dimension array and axes
arr11= np.array([[1,5,6],[8,7,9],[12,5,9]])
print(arr11)
sum_of_column= np.sum(arr11,axis=0)
print(sum_of_column)
sum_of_row= np.sum(arr11,axis=1)
print(sum_of_row)

[[ 1  5  6]
 [ 8  7  9]
 [12  5  9]]
[21 17 24]
[12 24 26]


In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr + arr2)

#broadcasting

print(arr + 5)

[ 7  9 11 13 15]
[ 6  7  8  9 10]


In [3]:
def generate_synthetic_data(num_samples=1000, num_features=5):
    np.random.seed(42)
    X = np.random.randn(num_samples, num_features)
    true_weights = np.array([1.5, -2.0, 3.5, 0.5, -1.0])
    y = X @ true_weights + np.random.randn(num_samples) * 0.1
    return X, y

def train_linear_regression(X, y):
    X_b = np.c_[np.ones((X.shape[0], 1)), X]
    theta_best = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
    return theta_best

def predict(X, theta):
    X_b = np.c_[np.ones((X.shape[0], 1)), X]
    return X_b @ theta

if __name__ == "__main__":
    X_train, y_train = generate_synthetic_data()
    weights = train_linear_regression(X_train, y_train)
    
    X_test = np.array([
        [1.0, 0.5, -1.2, 0.3, 0.8],
        [-0.5, 1.2, 0.1, -0.4, 0.9]
    ])
    predictions = predict(X_test, weights)
    
    print("Calculated Weights:", weights)
    print("Predictions:", predictions)

Calculated Weights: [-0.0047473   1.49876861 -1.99742466  3.49688057  0.50012403 -0.99595662]
Predictions: [-4.34767578 -3.89776371]
